Repository themoment-team/HiRecruit-server, pull requests merged in 2022-05, with the labels that each got.

#15 Add workflow codecov draft [초안]
  .github/workflows/workflow.yml
Labels: high

#17 Worker도메인 관련 코드 kotlin으로 마이그레이션
  src/main/java/site/hirecruit/hr/domain/worker/entity/WorkerEntity.java
  src/main/java/site/hirecruit/hr/domain/worker/entity/WorkerEntity.kt
  src/main/java/site/hirecruit/hr/domain/worker/repository/WorkerRepository.java
  src/main/java/site/hirecruit/hr/domain/worker/repository/WorkerRepository.kt
Labels: healthy

#18 SecurityConfig kotlin으로 마이그래이션
  src/main/java/site/hirecruit/hr/global/security/SecurityConfig.java
  src/main/java/site/hirecruit/hr/global/security/SecurityConfig.kt
Labels: healthy, high

#19 Add delete merged bot
  .github/delete-merged-branch-config.yml
Labels: healthy

#21 Auth domain kotlin migration 완료
  build.gradle
  src/main/java/site/hirecruit/hr/domain/auth/dto/OAuthAttributes.java
  src/main/java/site/hirecruit/hr/domain/auth/dto/OAuthAttributes.kt
  src/main/java/site/hirecruit/hr/domain/auth/dto/SessionUser.java
  src/main/java/site/hirecruit/hr/domain/auth/model/User.kt
  src/main/java/site/hirecruit/hr/domain/auth/service/CustomOAuth2UserService.java
  src/main/java/site/hirecruit/hr/domain/auth/service/CustomOAuth2UserService.kt
  src/main/java/site/hirecruit/hr/domain/auth/service/OAuth2ProcessorFacadeImpl.kt
  src/main/java/site/hirecruit/hr/domain/auth/service/OAuthProcessorFacade.kt
  src/main/java/site/hirecruit/hr/domain/auth/service/UserAuthService.java
  src/main/java/site/hirecruit/hr/domain/auth/service/UserAuthService.kt
  src/main/java/site/hirecruit/hr/domain/auth/service/UserAuthServiceImpl.java
  src/main/java/site/hirecruit/hr/domain/auth/service/UserAuthServiceImpl.kt
  src/main/java/site/hirecruit/hr/domain/auth/service/UserRegistrationGithubServiceImpl.java
  src/main/java/site/hirecruit/hr/domain/auth/service/UserRegistrationService.java
  src/main/java/site/hirecruit/hr/domain/auth/service/UserRegistrationService.kt
  src/main/java/site/hirecruit/hr/domain/auth/service/UserRegistrationServiceImpl.kt
  src/main/java/site/hirecruit/hr/domain/worker/entity/WorkerEntity.java
  src/main/java/site/hirecruit/hr/domain/worker/repository/WorkerRepository.java
  src/test/java/site/hirecruit/hr/domain/auth/service/OAuth2ProcessorFacadeImplTest.kt
Labels: healthy

#22 Migration/anonymous
  src/main/java/site/hirecruit/hr/domain/anonymous/controller/AnonymousController.java
  src/main/java/site/hirecruit/hr/domain/anonymous/dto/AnonymousDto.java
  src/main/java/site/hirecruit/hr/domain/anonymous/entity/AnonymousEntity.java
  src/main/java/site/hirecruit/hr/domain/anonymous/repository/AnonymousCustomRepository.java
  src/main/java/site/hirecruit/hr/domain/anonymous/repository/AnonymousCustomRepositoryImpl.java
  src/main/java/site/hirecruit/hr/domain/anonymous/repository/AnonymousRepository.java
  src/main/java/site/hirecruit/hr/domain/anonymous/service/AnonymousService.java
  src/main/java/site/hirecruit/hr/domain/mentee/entity/MenteeEntity.kt
  src/main/java/site/hirecruit/hr/domain/mentee/repository/AnonymousRepository.kt
  src/main/java/site/hirecruit/hr/domain/mentee/service/MenteeService.kt
  src/main/java/site/hirecruit/hr/domain/mentoring/service/MentoringService.kt
  src/test/java/site/hirecruit/hr/domain/anonymous/controller/AnonymousControllerTest.java
  src/test/java/site/hirecruit/hr/domain/anonymous/entity/AnonymousEntityTest.java
  src/test/java/site/hirecruit/hr/domain/anonymous/service/AnonymousServiceTest.java
  src/test/java/site/hirecruit/hr/domain/mentee/service/MenteeCoreServiceTest.kt
Labels: documentation, hotfix, high

#24 Feature/mentee [legacy code liquidation]
  build.gradle
  src/main/java/site/hirecruit/hr/domain/mentee/dto/MenteeDto.kt
  src/main/java/site/hirecruit/hr/domain/mentee/entity/MenteeEntity.kt
  src/main/java/site/hirecruit/hr/domain/mentee/repository/MenteeRepository.kt
  src/main/java/site/hirecruit/hr/domain/mentee/service/MenteeService.kt
  src/main/java/site/hirecruit/hr/domain/mentee/service/MenteeServiceImpl.kt
  src/main/java/site/hirecruit/hr/global/annotation/Dto.kt
  src/main/java/site/hirecruit/hr/global/config/ModelMapperConfig.java
  src/main/java/site/hirecruit/hr/global/config/ModelMapperConfig.kt
  src/main/java/site/hirecruit/hr/global/util/UtilEx.java
  src/main/java/site/hirecruit/hr/global/util/Utils.kt
  src/main/java/site/hirecruit/hr/modules/specification/Specification.kt
  src/test/java/site/hirecruit/hr/domain/mentee/service/MenteeCoreServiceTest.kt
Labels: enhancement

#25 Develop
  build.gradle
  src/main/java/site/hirecruit/hr/domain/anonymous/controller/AnonymousController.java
  src/main/java/site/hirecruit/hr/domain/anonymous/dto/AnonymousDto.java
  src/main/java/site/hirecruit/hr/domain/anonymous/entity/AnonymousEntity.java
  src/main/java/site/hirecruit/hr/domain/anonymous/repository/AnonymousCustomRepository.java
  src/main/java/site/hirecruit/hr/domain/anonymous/repository/AnonymousCustomRepositoryImpl.java
  src/main/java/site/hirecruit/hr/domain/anonymous/repository/AnonymousRepository.java
  src/main/java/site/hirecruit/hr/domain/anonymous/service/AnonymousService.java
  src/main/java/site/hirecruit/hr/domain/auth/dto/OAuthAttributes.java
  src/main/java/site/hirecruit/hr/domain/auth/dto/OAuthAttributes.kt
  src/main/java/site/hirecruit/hr/domain/auth/dto/SessionUser.java
  src/main/java/site/hirecruit/hr/domain/auth/model/User.kt
  src/main/java/site/hirecruit/hr/domain/auth/service/CustomOAuth2UserService.java
  src/main/java/site/hirecruit/hr/domain/auth/service/CustomOAuth2UserService.kt
  src/main/java/site/hirecruit/hr/domain/auth/service/OAuth2ProcessorFacadeImpl.kt
  src/main/java/site/hirecruit/hr/domain/auth/service/OAuthProcessorFacade.kt
  src/main/java/site/hirecruit/hr/domain/auth/service/UserAuthService.java
  src/main/java/site/hirecruit/hr/domain/auth/service/UserAuthService.kt
  src/main/java/site/hirecruit/hr/domain/auth/service/UserAuthServiceImpl.java
  src/main/java/site/hirecruit/hr/domain/auth/service/UserAuthServiceImpl.kt
  src/main/java/site/hirecruit/hr/domain/auth/service/UserRegistrationGithubServiceImpl.java
  src/main/java/site/hirecruit/hr/domain/auth/service/UserRegistrationService.java
  src/main/java/site/hirecruit/hr/domain/auth/service/UserRegistrationService.kt
  src/main/java/site/hirecruit/hr/domain/auth/service/UserRegistrationServiceImpl.kt
  src/main/java/site/hirecruit/hr/domain/mentee/dto/MenteeDto.kt
  src/main/java/site/hirecruit/hr/domain/mentee/entity/MenteeEntity.kt
  src/main/java/site/hirecruit/hr/domain/mentee/repository/MenteeRepository.kt
  src/main/java/site/hirecruit/hr/domain/mentee/service/MenteeService.kt
  src/main/java/site/hirecruit/hr/domain/mentee/service/MenteeServiceImpl.kt
  src/main/java/site/hirecruit/hr/domain/mentoring/service/MentoringService.kt
  src/main/java/site/hirecruit/hr/domain/worker/entity/WorkerEntity.java
  src/main/java/site/hirecruit/hr/domain/worker/repository/WorkerRepository.java
  src/main/java/site/hirecruit/hr/global/annotation/Dto.kt
  src/main/java/site/hirecruit/hr/global/config/ModelMapperConfig.java
  src/main/java/site/hirecruit/hr/global/config/ModelMapperConfig.kt
  src/main/java/site/hirecruit/hr/global/util/UtilEx.java
  src/main/java/site/hirecruit/hr/global/util/Utils.kt
  src/main/java/site/hirecruit/hr/modules/specification/Specification.kt
  src/test/java/site/hirecruit/hr/domain/anonymous/controller/AnonymousControllerTest.java
  src/test/java/site/hirecruit/hr/domain/anonymous/entity/AnonymousEntityTest.java
  src/test/java/site/hirecruit/hr/domain/anonymous/service/AnonymousServiceTest.java
  src/test/java/site/hirecruit/hr/domain/auth/service/OAuth2ProcessorFacadeImplTest.kt
  src/test/java/site/hirecruit/hr/domain/mentee/service/MenteeCoreServiceTest.kt
Labels: healthy

#26 Update readme
  README.md
Labels: documentation

#27 Create LICENSE [MIT]
  LICENSE
  README.md
Labels: documentation

#30 Add mentoring-application domain [entity 작업]
  src/main/java/site/hirecruit/hr/domain/mentoring/service/MentoringService.kt
  src/main/java/site/hirecruit/hr/domain/mentoringApplication/entity/MentoringApplication.kt
  src/main/java/site/hirecruit/hr/domain/mentoringApplication/entity/MentoringStatus.kt
Labels: enhancement, healthy

#29 Auth 도메인에 존재하던 Worker 의존성 제거
  src/main/java/site/hirecruit/hr/domain/auth/dto/AuthUserInfo.kt
  src/main/java/site/hirecruit/hr/domain/auth/entity/Role.kt
  src/main/java/site/hirecruit/hr/domain/auth/entity/UserEntity.kt
  src/main/java/site/hirecruit/hr/domain/auth/repository/UserRepository.kt
  src/main/java/site/hirecruit/hr/domain/auth/service/CustomOAuth2UserService.kt
  src/main/java/site/hirecruit/hr/domain/auth/service/OAuthProcessorFacade.kt
  src/main/java/site/hirecruit/hr/domain/auth/service/UserAuthService.kt
  src/main/java/site/hirecruit/hr/domain/auth/service/impl/OAuth2ProcessorFacadeImpl.kt
  src/main/java/site/hirecruit/hr/domain/auth/service/impl/UserAuthServiceImpl.kt
  src/main/java/site/hirecruit/hr/domain/auth/service/impl/UserRegistrationServiceImpl.kt
  src/main/java/site/hirecruit/hr/domain/worker/entity/WorkerEntity.kt
  src/test/java/site/hirecruit/hr/domain/auth/service/OAuth2ProcessorFacadeImplTest.kt
Labels: healthy

#31 Hotfix/authuserinfo open
  src/main/java/site/hirecruit/hr/domain/auth/dto/AuthUserInfo.kt
Labels: hotfix

#32 Fix existBy~ should not be null
  src/main/java/site/hirecruit/hr/domain/mentee/repository/MenteeRepository.kt
  src/main/java/site/hirecruit/hr/domain/mentee/service/MenteeServiceImpl.kt
Labels: hotfix, healthy

#33 Local Profile Test
  build.gradle
  src/test/java/site/hirecruit/hr/domain/auth/service/OAuth2ProcessorFacadeImplTest.kt
  src/test/java/site/hirecruit/hr/domain/mentee/service/MenteeCoreServiceTest.kt
  src/test/java/site/hirecruit/hr/domain/test_util/LocalTest.kt
Labels: hotfix, healthy

#34 Feature/mentoring details
  src/main/java/site/hirecruit/hr/domain/mentoringApplication/entity/MentoringApplication.kt
  src/main/java/site/hirecruit/hr/domain/mentoringApplication/entity/MentoringStatus.kt
  src/main/java/site/hirecruit/hr/domain/mentoringRequestDetails/entity/MentoringRequestDetailsEntity.kt
Labels: documentation, enhancement

#36 임시 회원 등록 로직
  src/main/java/site/hirecruit/hr/domain/auth/dto/AuthUserInfo.kt
  src/main/java/site/hirecruit/hr/domain/auth/entity/TempUserEntity.kt
  src/main/java/site/hirecruit/hr/domain/auth/repository/TempUserRepository.kt
  src/main/java/site/hirecruit/hr/domain/auth/service/TempUserRegistrationService.kt
  src/main/java/site/hirecruit/hr/domain/auth/service/impl/OAuth2ProcessorFacadeImpl.kt
  src/main/java/site/hirecruit/hr/domain/auth/service/impl/TempUserRegistrationServiceImpl.kt
  src/main/java/site/hirecruit/hr/domain/auth/service/impl/UserRegistrationServiceImpl.kt
  src/test/java/site/hirecruit/hr/domain/auth/service/OAuth2ProcessorFacadeImplTest.kt
  src/test/java/site/hirecruit/hr/domain/auth/service/impl/TempUserRegistrationServiceImplTest.kt
Labels: enhancement, best-review, healthy

#37 회원 인증 및 세션 등록 로직 완료
  src/main/java/site/hirecruit/hr/domain/auth/aop/UserAuthAspect.kt
  src/main/java/site/hirecruit/hr/domain/auth/dto/AuthUserInfo.kt
  src/main/java/site/hirecruit/hr/domain/auth/entity/TempUserEntity.kt
  src/main/java/site/hirecruit/hr/domain/auth/repository/UserCustomRepository.kt
  src/main/java/site/hirecruit/hr/domain/auth/repository/UserCustomRepositoryImpl.kt
  src/main/java/site/hirecruit/hr/domain/auth/repository/UserRepository.kt
  src/main/java/site/hirecruit/hr/domain/auth/service/UserAuthService.kt
  src/main/java/site/hirecruit/hr/domain/auth/service/impl/TempUserRegistrationServiceImpl.kt
  src/main/java/site/hirecruit/hr/domain/auth/service/impl/UserAuthServiceImpl.kt
  src/test/java/site/hirecruit/hr/domain/auth/service/impl/TempUserRegistrationServiceImplTest.kt
  src/test/java/site/hirecruit/hr/domain/auth/service/impl/UserAuthServiceImplTest.kt
Labels: healthy

#38 embedded redis의 기본 포트가 실행중일 때 다른 포트로 실행하는 로직 추가
  src/main/java/site/hirecruit/hr/global/config/EmbeddedRedisConfig.kt
Labels: healthy

#39 Update app, querydsl config java -> kotlin 으로 변경 함.
  build.gradle
  build.gradle.kts
  src/main/java/site/hirecruit/hr/HRApplication.java
  src/main/java/site/hirecruit/hr/HRApplication.kt
  src/main/java/site/hirecruit/hr/global/config/QuerydslConfig.java
  src/main/java/site/hirecruit/hr/global/config/QuerydslConfig.kt
Labels: hotfix, healthy

#41 UserCustomRepositoryImpl 구현
  build.gradle.kts
  src/main/java/site/hirecruit/hr/domain/auth/dto/AuthUserInfo.kt
  src/main/java/site/hirecruit/hr/domain/auth/entity/UserEntity.kt
  src/main/java/site/hirecruit/hr/domain/auth/repository/UserCustomRepositoryImpl.kt
  src/main/java/site/hirecruit/hr/domain/worker/entity/WorkerEntity.kt
  src/main/java/site/hirecruit/hr/domain/worker/repository/WorkerRepository.kt
  src/test/java/site/hirecruit/hr/domain/auth/repository/UserCustomRepositoryImplTest.kt
Labels: healthy

#42 jacoco report 실패하던 문제 해결
  build.gradle.kts
  gradle.properties
Labels: healthy

#43 WorkerEntty devYear, giveLink 프로퍼티 추가
  src/main/java/site/hirecruit/hr/domain/worker/entity/WorkerEntity.kt
Labels: documentation, healthy

#44 Session에 있는 user정보를 가져오는 annotation 생성
  src/main/java/site/hirecruit/hr/domain/auth/aop/UserAuthAspect.kt
  src/main/java/site/hirecruit/hr/global/annotation/CurrentAuthUserInfo.kt
  src/main/java/site/hirecruit/hr/global/config/WebConfig.kt
  src/main/java/site/hirecruit/hr/global/data/SessionAttribute.kt
  src/main/java/site/hirecruit/hr/global/resolver/CurrentAuthUserInfoResolver.kt
Labels: healthy

#45 Feature/aws sns config
  .gitignore
  build.gradle.kts
  src/main/java/site/hirecruit/hr/modules/specification/Specification.kt
  src/main/java/site/hirecruit/hr/thirdParty/aws/config/AwsSnsConfig.kt
  src/main/java/site/hirecruit/hr/thirdParty/aws/service/CredentialService.kt
Labels: documentation, enhancement

#46 Feature/aws sns [create topic 피쳐 개발]
  src/main/java/site/hirecruit/hr/thirdParty/aws/service/CredentialService.kt
  src/main/java/site/hirecruit/hr/thirdParty/aws/sns/controller/SnsController.kt
  src/main/java/site/hirecruit/hr/thirdParty/aws/sns/service/SnsTopicFactoryService.kt
  src/main/java/site/hirecruit/hr/thirdParty/aws/sns/service/SnsTopicFactoryServiceImpl.kt
  src/main/java/site/hirecruit/hr/thirdParty/aws/sns/service/facade/SnsTopicSubSystemFacade.kt
  src/test/java/site/hirecruit/hr/thirdParty/aws/sns/service/SnsTopicFactoryServiceImplTest.kt
Labels: documentation, enhancement, question, best-review, healthy, Not completed

#47 Feature/aws sns modules [display all topic: 생성된 모든 토픽 가져오기]
  src/main/java/site/hirecruit/hr/thirdParty/aws/sns/service/SnsTopicFactoryService.kt
  src/main/java/site/hirecruit/hr/thirdParty/aws/sns/service/SnsTopicFactoryServiceImpl.kt
  src/main/java/site/hirecruit/hr/thirdParty/aws/sns/service/facade/SnsTopicSubSystemFacade.kt
  src/test/java/site/hirecruit/hr/thirdParty/aws/sns/service/SnsTopicFactoryServiceImplTest.kt
Labels: documentation, enhancement, healthy

#48 Develop
  .gitignore
  build.gradle.kts
  gradle.properties
  src/main/java/site/hirecruit/hr/domain/auth/aop/UserAuthAspect.kt
  src/main/java/site/hirecruit/hr/domain/auth/dto/AuthUserInfo.kt
  src/main/java/site/hirecruit/hr/domain/auth/entity/UserEntity.kt
  src/main/java/site/hirecruit/hr/domain/auth/repository/UserCustomRepositoryImpl.kt
  src/main/java/site/hirecruit/hr/domain/worker/entity/WorkerEntity.kt
  src/main/java/site/hirecruit/hr/domain/worker/repository/WorkerRepository.kt
  src/main/java/site/hirecruit/hr/global/annotation/CurrentAuthUserInfo.kt
  src/main/java/site/hirecruit/hr/global/config/WebConfig.kt
  src/main/java/site/hirecruit/hr/global/data/SessionAttribute.kt
  src/main/java/site/hirecruit/hr/global/resolver/CurrentAuthUserInfoResolver.kt
  src/main/java/site/hirecruit/hr/modules/specification/Specification.kt
  src/main/java/site/hirecruit/hr/thirdParty/aws/config/AwsSnsConfig.kt
  src/main/java/site/hirecruit/hr/thirdParty/aws/service/CredentialService.kt
  src/main/java/site/hirecruit/hr/thirdParty/aws/sns/controller/SnsController.kt
  src/main/java/site/hirecruit/hr/thirdParty/aws/sns/service/SnsTopicFactoryService.kt
  src/main/java/site/hirecruit/hr/thirdParty/aws/sns/service/SnsTopicFactoryServiceImpl.kt
  src/main/java/site/hirecruit/hr/thirdParty/aws/sns/service/facade/SnsTopicSubSystemFacade.kt
  src/test/java/site/hirecruit/hr/domain/auth/repository/UserCustomRepositoryImplTest.kt
  src/test/java/site/hirecruit/hr/thirdParty/aws/sns/service/SnsTopicFactoryServiceImplTest.kt
Labels: documentation, healthy

#49 회원가입 로직 완료
  build.gradle.kts
  src/main/java/site/hirecruit/hr/domain/auth/aop/UserAuthAspect.kt
  src/main/java/site/hirecruit/hr/domain/auth/aop/UserRegistrationAspect.kt
  src/main/java/site/hirecruit/hr/domain/auth/controller/AuthController.kt
  src/main/java/site/hirecruit/hr/domain/auth/dto/UserRegistrationDto.kt
  src/main/java/site/hirecruit/hr/domain/auth/entity/Role.kt
  src/main/java/site/hirecruit/hr/domain/auth/entity/UserEntity.kt
  src/main/java/site/hirecruit/hr/domain/auth/service/EmailAuthenticationService.kt
  src/main/java/site/hirecruit/hr/domain/auth/service/UserRegistrationService.kt
  src/main/java/site/hirecruit/hr/domain/auth/service/impl/EmailAuthenticationServiceImpl.kt
  src/main/java/site/hirecruit/hr/domain/auth/service/impl/UserRegistrationServiceImpl.kt
  src/main/java/site/hirecruit/hr/domain/worker/dto/WorkerDto.kt
  src/main/java/site/hirecruit/hr/global/event/UserRegistrationEvent.kt
  src/main/java/site/hirecruit/hr/global/event/UserRegistrationEventHandler.kt
  src/test/java/site/hirecruit/hr/domain/auth/service/impl/UserRegistrationServiceImplTest.kt
Labels: documentation, healthy

#50 Feature/aws sns sub email
  src/main/java/site/hirecruit/hr/thirdParty/aws/config/AwsSnsConfig.kt
  src/main/java/site/hirecruit/hr/thirdParty/aws/sns/ProtocolType.kt
  src/main/java/site/hirecruit/hr/thirdParty/aws/sns/service/SnsTopicFactoryService.kt
  src/main/java/site/hirecruit/hr/thirdParty/aws/sns/service/SnsTopicFactoryServiceImpl.kt
  src/main/java/site/hirecruit/hr/thirdParty/aws/sns/service/facade/SnsTopicSubSystemFacade.kt
  src/test/java/site/hirecruit/hr/thirdParty/aws/sns/service/SnsTopicFactoryServiceImplTest.kt
Labels: documentation, enhancement, Not completed

#52 Update README Application Settings
  README.md
Labels: documentation

#53 Auth Aspect classes test code
  src/main/java/site/hirecruit/hr/domain/auth/aop/UserAuthAspect.kt
  src/main/java/site/hirecruit/hr/domain/auth/aop/UserRegistrationAspect.kt
  src/main/java/site/hirecruit/hr/domain/auth/controller/AuthController.kt
  src/test/java/site/hirecruit/hr/domain/auth/aop/UserAuthAspectTest.kt
  src/test/java/site/hirecruit/hr/domain/auth/aop/UserRegistrationAspectTest.kt
Labels: healthy

#55 Feature/sns architectural improvements
  src/main/java/site/hirecruit/hr/thirdParty/aws/sns/service/SnsTopicFactoryServiceImpl.kt
  src/main/java/site/hirecruit/hr/thirdParty/aws/sns/service/facade/SnsClientSubSystemFacade.kt
  src/main/java/site/hirecruit/hr/thirdParty/aws/sns/service/facade/SnsRequestSubSystemFacade.kt
  src/test/java/site/hirecruit/hr/thirdParty/aws/sns/service/SnsTopicFactoryServiceImplTest.kt
Labels: documentation, hotfix, healthy

#56 Feature/sns facade improvement
  src/main/java/site/hirecruit/hr/thirdParty/aws/sns/service/SnsTopicFactoryServiceImpl.kt
  src/main/java/site/hirecruit/hr/thirdParty/aws/sns/service/facade/SnsClientSubSystemFacade.kt
  src/main/java/site/hirecruit/hr/thirdParty/aws/sns/service/facade/SnsRequestSubSystemFacade.kt
  src/main/java/site/hirecruit/hr/thirdParty/aws/sns/service/facade/impl/SnsClientSubSystemFacadeImpl.kt
  src/main/java/site/hirecruit/hr/thirdParty/aws/sns/service/facade/impl/SnsRequestSubSystemFacadeImpl.kt
  src/test/java/site/hirecruit/hr/thirdParty/aws/sns/service/SnsTopicFactoryServiceImplTest.kt
Labels: documentation, healthy, Not completed

#58 Worker 도메인 생성, 수정, 조회(로그인된 유저) 기능 완료
  src/main/java/site/hirecruit/hr/domain/auth/repository/UserRepository.kt
  src/main/java/site/hirecruit/hr/domain/auth/service/impl/UserRegistrationServiceImpl.kt
  src/main/java/site/hirecruit/hr/domain/worker/aop/WorkerUpdateColumnsVerifierAspect.kt
  src/main/java/site/hirecruit/hr/domain/worker/controller/WorkerController.kt
  src/main/java/site/hirecruit/hr/domain/worker/dto/WorkerDto.kt
  src/main/java/site/hirecruit/hr/domain/worker/entity/WorkerEntity.kt
  src/main/java/site/hirecruit/hr/domain/worker/repository/WorkerRepository.kt
  src/main/java/site/hirecruit/hr/domain/worker/service/AuthUserWorkerService.kt
  src/main/java/site/hirecruit/hr/domain/worker/service/AuthUserWorkerServiceImpl.kt
  src/main/java/site/hirecruit/hr/domain/worker/service/WorkerRegistrationService.kt
  src/main/java/site/hirecruit/hr/domain/worker/service/WorkerRegistrationServiceImpl.kt
  src/main/java/site/hirecruit/hr/global/event/UserRegistrationEvent.kt
  src/main/java/site/hirecruit/hr/global/event/UserRegistrationEventHandler.kt
  src/test/java/site/hirecruit/hr/domain/worker/aop/WorkerUpdateColumnsVerifierAspectTest.kt
  src/test/java/site/hirecruit/hr/domain/worker/service/AuthUserWorkerServiceImplTest.kt
  src/test/java/site/hirecruit/hr/domain/worker/service/WorkerRegistrationServiceImplTest.kt
  src/test/java/site/hirecruit/hr/test_config/DataJpaTestConfig.kt
Labels: healthy

#60 Fix develop branch build fail
  src/main/java/site/hirecruit/hr/domain/auth/dto/AuthUserInfo.kt
  src/main/java/site/hirecruit/hr/domain/auth/service/impl/UserRegistrationServiceWithoutEmailAuthentication.kt
  src/main/java/site/hirecruit/hr/domain/worker/aop/WorkerUpdateColumnsVerifierAspect.kt
  src/main/java/site/hirecruit/hr/domain/worker/service/AuthUserWorkerService.kt
  src/test/java/site/hirecruit/hr/domain/auth/service/impl/UserRegistrationServiceImplTest.kt
  src/test/java/site/hirecruit/hr/domain/auth/service/impl/UserRegistrationServiceWithoutEmailAuthenticationTest.kt
  src/test/java/site/hirecruit/hr/domain/worker/aop/WorkerUpdateColumnsVerifierAspectTest.kt
Labels: hotfix, high

#61 Worker domain refactoring
  src/main/java/site/hirecruit/hr/domain/worker/aop/WorkerUpdateColumnsVerifierAspect.kt
  src/main/java/site/hirecruit/hr/domain/worker/dto/WorkerDto.kt
  src/main/java/site/hirecruit/hr/domain/worker/entity/WorkerEntity.kt
  src/main/java/site/hirecruit/hr/domain/worker/service/AuthUserWorkerServiceImpl.kt
  src/main/java/site/hirecruit/hr/domain/worker/service/WorkerRegistrationService.kt
  src/main/java/site/hirecruit/hr/domain/worker/service/WorkerRegistrationServiceImpl.kt
  src/test/java/site/hirecruit/hr/domain/auth/aop/UserRegistrationAspectTest.kt
  src/test/java/site/hirecruit/hr/domain/auth/service/impl/UserRegistrationServiceImplTest.kt
  src/test/java/site/hirecruit/hr/domain/auth/service/impl/UserRegistrationServiceWithoutEmailAuthenticationTest.kt
  src/test/java/site/hirecruit/hr/domain/worker/aop/WorkerUpdateColumnsVerifierAspectTest.kt
  src/test/java/site/hirecruit/hr/domain/worker/service/AuthUserWorkerServiceImplTest.kt
  src/test/java/site/hirecruit/hr/domain/worker/service/WorkerRegistrationServiceImplTest.kt
Labels: healthy, high

#63 Fix Type mismatch
  src/main/java/site/hirecruit/hr/domain/worker/entity/WorkerEntity.kt
  src/main/java/site/hirecruit/hr/domain/worker/service/WorkerRegistrationServiceImpl.kt
Labels: hotfix, high

#62 Company도메인 Entity설계 및 생성/조회 로직 작성
  src/main/java/site/hirecruit/hr/domain/company/controller/CompanyController.kt
  src/main/java/site/hirecruit/hr/domain/company/dto/CompanyDto.kt
  src/main/java/site/hirecruit/hr/domain/company/entity/CompanyEntity.kt
  src/main/java/site/hirecruit/hr/domain/company/repository/CompanyRepository.kt
  src/main/java/site/hirecruit/hr/domain/company/service/CompanyService.kt
  src/test/java/site/hirecruit/hr/domain/company/service/CompanyServiceTest.kt
Labels: healthy

#64 Feature/GitHub ci action
  .github/workflow/github-action-ci-script.yml
Labels: documentation, enhancement, high

#65 Develop
  .github/workflow/github-action-ci-script.yml
  src/main/java/site/hirecruit/hr/domain/company/controller/CompanyController.kt
  src/main/java/site/hirecruit/hr/domain/company/dto/CompanyDto.kt
  src/main/java/site/hirecruit/hr/domain/company/entity/CompanyEntity.kt
  src/main/java/site/hirecruit/hr/domain/company/repository/CompanyRepository.kt
  src/main/java/site/hirecruit/hr/domain/company/service/CompanyService.kt
  src/main/java/site/hirecruit/hr/domain/worker/aop/WorkerUpdateColumnsVerifierAspect.kt
  src/main/java/site/hirecruit/hr/domain/worker/dto/WorkerDto.kt
  src/main/java/site/hirecruit/hr/domain/worker/entity/WorkerEntity.kt
  src/main/java/site/hirecruit/hr/domain/worker/service/AuthUserWorkerServiceImpl.kt
  src/main/java/site/hirecruit/hr/domain/worker/service/WorkerRegistrationService.kt
  src/main/java/site/hirecruit/hr/domain/worker/service/WorkerRegistrationServiceImpl.kt
  src/test/java/site/hirecruit/hr/domain/auth/aop/UserRegistrationAspectTest.kt
  src/test/java/site/hirecruit/hr/domain/auth/service/impl/UserRegistrationServiceImplTest.kt
  src/test/java/site/hirecruit/hr/domain/auth/service/impl/UserRegistrationServiceWithoutEmailAuthenticationTest.kt
  src/test/java/site/hirecruit/hr/domain/company/service/CompanyServiceTest.kt
  src/test/java/site/hirecruit/hr/domain/worker/aop/WorkerUpdateColumnsVerifierAspectTest.kt
  src/test/java/site/hirecruit/hr/domain/worker/service/AuthUserWorkerServiceImplTest.kt
  src/test/java/site/hirecruit/hr/domain/worker/service/WorkerRegistrationServiceImplTest.kt
Labels: documentation, high

#68 Update github-action-ci-script.yml
  .github/workflows/github-action-ci-script.yml
Labels: bug, hotfix

#71 Develop
  .github/workflows/github-action-ci-script.yml
  eventUpdate.md
Labels: documentation, enhancement

#73 Add deploy spec img
  README.md
  assets/img/hr-backend-deploy-spec.png
Labels: documentation

#72 Feature 회원가입시 Security context에 유저 정보 update
  src/main/java/site/hirecruit/hr/domain/auth/aop/UserAuthAspect.kt
  src/main/java/site/hirecruit/hr/domain/auth/aop/UserRegistrationAspect.kt
  src/main/java/site/hirecruit/hr/domain/auth/service/SecurityContextAccessService.kt
  src/main/java/site/hirecruit/hr/domain/auth/service/impl/UserSessionAuthServiceImpl.kt
  src/main/java/site/hirecruit/hr/global/security/SecurityConfig.kt
  src/test/java/site/hirecruit/hr/domain/auth/aop/UserRegistrationAspectTest.kt
  src/test/java/site/hirecruit/hr/domain/auth/service/impl/UserSessionAuthServiceImplTest.kt
Labels: healthy

#75 Update 순서를 바꾸었다
  README.md
Labels: documentation, healthy, high

#74 Feature/hr-app-docker-image
  Dockerfile
  build.gradle.kts
Labels: documentation, enhancement, healthy

#80 Feature/test cd action script
  .github/workflows/github-action-cd-script.yml
  .github/workflows/github-action-ci-script.yml
Labels: documentation, enhancement

#84 Hotfix WorkerUpdateColumnsVerifierAspect exception message 잘못 명시
  src/main/java/site/hirecruit/hr/domain/worker/aop/WorkerUpdateColumnsVerifierAspect.kt
Labels: hotfix

#87 Local profile용 cors 설정
  src/main/java/site/hirecruit/hr/global/config/LocalCorsConfig.kt
Labels: documentation
