Repository themoment-team/HiRecruit-server, pull requests merged in 2022-08, with the labels that each got.

#274 User 도메인 mapstruct이전 완료
  src/main/java/site/hirecruit/hr/domain/user/mapper/TempUserEntityMapper.kt
  src/main/java/site/hirecruit/hr/domain/user/mapper/UserEntityMapper.kt
  src/main/java/site/hirecruit/hr/domain/user/service/TempUserRegistrationService.kt
  src/main/java/site/hirecruit/hr/domain/user/service/UserUpdateServiceImpl.kt
  src/main/java/site/hirecruit/hr/domain/user/service/WorkerUserRegistrationService.kt
Labels: improvement

#275 Hotfix - 도커파일이 캐시 된줄알았던 이슈 에 대한 해결
  .github/workflows/github-action-ci.yml
  .github/workflows/github-action-prod-cd.yml
  Dockerfile
  task-definition.json
Labels: hotfix, healthy, DevOps

#273 auth 도메인에 있던 user로직 모두 user 패키지로 이전
  src/main/java/site/hirecruit/hr/batch/github_login_id/job/AddGithubLoginIdJobConfiguration.kt
  src/main/java/site/hirecruit/hr/domain/auth/dto/mapper/AuthUserInfoMapper.kt
  src/main/java/site/hirecruit/hr/domain/auth/service/impl/TempUserRegistrationServiceImpl.kt
  src/main/java/site/hirecruit/hr/domain/auth/service/impl/UserSessionAuthServiceImpl.kt
  src/main/java/site/hirecruit/hr/domain/user/aop/UserRegistrationAspect.kt
  src/main/java/site/hirecruit/hr/domain/user/controller/UserController.kt
  src/main/java/site/hirecruit/hr/domain/user/entity/TempUserEntity.kt
  src/main/java/site/hirecruit/hr/domain/user/mapper/TempUserEntityMapper.kt
  src/main/java/site/hirecruit/hr/domain/user/repository/TempUserRepository.kt
  src/main/java/site/hirecruit/hr/domain/user/service/TempUserRegistrationService.kt
  src/test/java/site/hirecruit/hr/domain/auth/aop/UserRegistrationAspectTest.kt
  src/test/java/site/hirecruit/hr/domain/auth/service/impl/TempUserRegistrationServiceImplTest.kt
  src/test/java/site/hirecruit/hr/domain/auth/service/impl/UserSessionAuthServiceImplTest.kt
Labels: improvement

#276 Develop
  .github/workflows/github-action-ci.yml
  .github/workflows/github-action-prod-cd.yml
  Dockerfile
  build.gradle.kts
  entrypoint.sh
  src/main/java/site/hirecruit/hr/batch/github_login_id/job/AddGithubLoginIdJobConfiguration.kt
  src/main/java/site/hirecruit/hr/domain/auth/dto/mapper/AuthUserInfoMapper.kt
  src/main/java/site/hirecruit/hr/domain/auth/service/impl/TempUserRegistrationServiceImpl.kt
  src/main/java/site/hirecruit/hr/domain/auth/service/impl/UserSessionAuthServiceImpl.kt
  src/main/java/site/hirecruit/hr/domain/user/aop/UserRegistrationAspect.kt
  src/main/java/site/hirecruit/hr/domain/user/controller/UserController.kt
  src/main/java/site/hirecruit/hr/domain/user/entity/TempUserEntity.kt
  src/main/java/site/hirecruit/hr/domain/user/mapper/TempUserEntityMapper.kt
  src/main/java/site/hirecruit/hr/domain/user/mapper/UserEntityMapper.kt
  src/main/java/site/hirecruit/hr/domain/user/repository/TempUserRepository.kt
  src/main/java/site/hirecruit/hr/domain/user/service/TempUserRegistrationService.kt
  src/main/java/site/hirecruit/hr/domain/user/service/UserUpdateServiceImpl.kt
  src/main/java/site/hirecruit/hr/domain/user/service/WorkerUserRegistrationService.kt
  src/test/java/site/hirecruit/hr/domain/auth/aop/UserRegistrationAspectTest.kt
  src/test/java/site/hirecruit/hr/domain/auth/service/impl/TempUserRegistrationServiceImplTest.kt
  src/test/java/site/hirecruit/hr/domain/auth/service/impl/UserSessionAuthServiceImplTest.kt
  task-definition.json
Labels: documentation

#277 WorkerUserRegistrationService test code작성
  src/test/java/site/hirecruit/hr/domain/user/service/WorkerUserRegistrationServiceTest.kt
Labels: improvement

#279 Hotfix 회원가입 로직
  src/main/java/site/hirecruit/hr/domain/user/service/WorkerUserRegistrationService.kt
  src/main/java/site/hirecruit/hr/domain/worker/mapper/WorkerInfoDtoMapper.kt
  src/main/java/site/hirecruit/hr/domain/worker/service/AuthUserWorkerServiceImpl.kt
Labels: hotfix

#280 worker 도메인에 mapstruct 도입
  src/main/java/site/hirecruit/hr/domain/worker/mapper/WorkerEntityMapper.kt
  src/main/java/site/hirecruit/hr/domain/worker/mapper/WorkerInfoDtoMapper.kt
  src/main/java/site/hirecruit/hr/domain/worker/service/WorkerRegistrationServiceImpl.kt
Labels: improvement

#281 company도메인 mapstruct 적용
  src/main/java/site/hirecruit/hr/domain/company/mapper/CompanyEntityMapper.kt
  src/main/java/site/hirecruit/hr/domain/company/mapper/CompanyInfoDtoMapper.kt
  src/main/java/site/hirecruit/hr/domain/company/service/CompanyService.kt
  src/test/java/site/hirecruit/hr/domain/company/service/CompanyServiceTest.kt
Labels: improvement

#282 프로필 등록 통합테스트
  build.gradle.kts
  src/main/java/site/hirecruit/hr/domain/user/controller/UserRegistrationController.kt
  src/main/java/site/hirecruit/hr/domain/worker/repository/WorkerRepository.kt
  src/test/java/site/hirecruit/hr/domain/user/service/ProfileRegistrationIntegratedTest.kt
Labels: improvement
