Repository themoment-team/HiRecruit-server, pull requests merged in 2022-06, with the labels that each got.

#89 Fix cannot found mainClass error
  build.gradle.kts
Labels: bug, hotfix, high

#92 FIx gradle build 후 jar 파일이 실행안되는 현상 해결
  build.gradle.kts
Labels: documentation, hotfix

#94 Fix typo jar name
  build.gradle.kts
Labels: hotfix

#95 Fix session발급 후 프론트앤드로 session cookie가 전달되지 않은 현상
  src/main/java/site/hirecruit/hr/global/security/SecurityConfig.kt
  src/main/java/site/hirecruit/hr/global/security/handler/OAuthLoginSuccessHandler.kt
  src/main/resources/application.yml
Labels: hotfix

#96 Feature Bean Validator Exception handling
  src/main/java/site/hirecruit/hr/global/exception/GlobalExceptionHandler.kt
  src/main/java/site/hirecruit/hr/global/exception/model/ExceptionResponseEntity.kt
Labels: documentation

#86 Feature/cd action script 와 CI script 를 연결 함 [reusable workflow]
  .github/workflows/github-action-ci-script.yml
  .github/workflows/github-action-test-cd-script.yml
  appspec.yml
  execute-deploy.sh
  src/docs/tag-descriptions.yml
Labels: bug, Not completed

#100 Add 운영환경에서 테스트 전용 profile(prod-test) 추가
  src/main/resources/application-prod-test.yml
Labels: documentation

#99 Validator annotation 적용
  src/main/java/site/hirecruit/hr/domain/auth/dto/UserRegistrationDto.kt
  src/main/java/site/hirecruit/hr/domain/company/controller/CompanyController.kt
  src/main/java/site/hirecruit/hr/domain/company/dto/CompanyDto.kt
  src/main/java/site/hirecruit/hr/domain/worker/controller/WorkerController.kt
  src/main/java/site/hirecruit/hr/domain/worker/dto/WorkerDto.kt
  src/test/java/site/hirecruit/hr/domain/auth/aop/UserRegistrationAspectTest.kt
  src/test/java/site/hirecruit/hr/domain/auth/service/impl/UserRegistrationServiceImplTest.kt
  src/test/java/site/hirecruit/hr/domain/auth/service/impl/UserRegistrationServiceWithoutEmailAuthenticationTest.kt
  src/test/java/site/hirecruit/hr/domain/company/service/CompanyServiceTest.kt
  src/test/java/site/hirecruit/hr/domain/worker/service/WorkerRegistrationServiceImplTest.kt
Labels: documentation

#101 Update Infrastructure png
  assets/img/hr-backend-deploy-spec.png
Labels: documentation

#102 Develop
  assets/img/hr-backend-deploy-spec.png
  src/main/java/site/hirecruit/hr/domain/auth/dto/UserRegistrationDto.kt
  src/main/java/site/hirecruit/hr/domain/company/controller/CompanyController.kt
  src/main/java/site/hirecruit/hr/domain/company/dto/CompanyDto.kt
  src/main/java/site/hirecruit/hr/domain/worker/controller/WorkerController.kt
  src/main/java/site/hirecruit/hr/domain/worker/dto/WorkerDto.kt
  src/main/java/site/hirecruit/hr/global/exception/GlobalExceptionHandler.kt
  src/main/resources/application-prod-test.yml
  src/test/java/site/hirecruit/hr/domain/auth/aop/UserRegistrationAspectTest.kt
  src/test/java/site/hirecruit/hr/domain/auth/service/impl/UserRegistrationServiceImplTest.kt
  src/test/java/site/hirecruit/hr/domain/auth/service/impl/UserRegistrationServiceWithoutEmailAuthenticationTest.kt
  src/test/java/site/hirecruit/hr/domain/company/service/CompanyServiceTest.kt
  src/test/java/site/hirecruit/hr/domain/worker/service/WorkerRegistrationServiceImplTest.kt
Labels: documentation

#103 Hotfix/zip to s3
  .github/workflows/github-action-ci-script.yml
  .github/workflows/github-action-test-cd-script.yml
Labels: documentation, hotfix, high

#104 Feature/logback to cloud watch
  .gitignore
  build.gradle.kts
Labels: documentation, enhancement, healthy

#105 SecurityConfig에 prod-test프로필 추가
  src/main/java/site/hirecruit/hr/global/security/SecurityConfig.kt
Labels: documentation

#107 Add gradle build action, unit test result reporter
  .github/workflows/github-action-ci-script.yml
Labels: documentation, enhancement

#108 Update uses gradle action
  .github/workflows/github-action-ci-script.yml
Labels: bug, hotfix

#110 Update eventUpdate.md
  eventUpdate.md
Labels: DevOps

#111 Update execute-deploy.sh
  execute-deploy.sh
Labels: DevOps

#112 Feature/some event
  .github/workflows/github-action-ecs-cd.yml
  execute-deploy.sh
Labels: bug, hotfix, DevOps

#114 Fix Script at specified location: execute-deploy.sh failed to close STDOUT
  appspec.yml
  execute-deploy.sh
Labels: bug, hotfix, DevOps

#115 prod-test 프로필 cors 설정
  src/main/java/site/hirecruit/hr/global/config/LocalCorsConfig.kt
Labels: documentation

#116 Fix 잘못 설정한 cors url
  src/main/java/site/hirecruit/hr/global/config/LocalCorsConfig.kt
Labels: documentation

#117 oauth2 redirect-base-uri profile 별 설정 완료
  src/main/resources/application-local.yml
  src/main/resources/application-prod-test.yml
  src/main/resources/application.yml
Labels: documentation

#118 Session cookie의 도메인을 설정했습니다
  src/main/resources/application-prod-test.yml
Labels: documentation

#119 Cookie config class 설정
  src/main/java/site/hirecruit/hr/global/config/CookieConfig.kt
Labels: documentation

#121 Revert "Cookie config class 설정"
  src/main/java/site/hirecruit/hr/global/config/CookieConfig.kt
Labels: hotfix

#122 session cookie domain 설정
  src/main/resources/application-local.yml
  src/main/resources/application-prod-test.yml
Labels: documentation

#128 prod-test cookie설정 및 security config 세션 설정
  src/main/java/site/hirecruit/hr/global/security/SecurityConfig.kt
  src/main/java/site/hirecruit/hr/global/security/handler/OAuthLoginSuccessHandler.kt
  src/main/resources/application-local.yml
  src/main/resources/application-prod-test.yml
Labels: documentation

#129 Fix cookie domain typo
  src/main/resources/application-prod-test.yml
Labels: hotfix

#131 Redis host 변경 및 컨테이너 수준 변경
  Dockerfile
  task-definition.json
Labels: DevOps

#132 Add error log 발생시키는 controller
  src/main/java/site/hirecruit/hr/health/HealthCheckController.kt
Labels: documentation, enhancement, DevOps

#134 OAuth2 login 후 보내주는 is-first query parame sanke_case로 변경
  src/main/java/site/hirecruit/hr/global/security/handler/OAuthLoginSuccessHandler.kt
Labels: documentation

#137 Hotfix user registration API companyId가 null이 아니여도 400 BadRequest 반환
  src/main/java/site/hirecruit/hr/domain/worker/dto/WorkerDto.kt
Labels: hotfix

#136 운영환경(prod) 전용 properties 생성
  build.gradle.kts
  src/main/resources/application-prod.yml
Labels: documentation

#135 prod-test프로필의 Session Timeout 1일로 설정
  src/main/resources/application-prod-test.yml
Labels: documentation

#133 Mysql 기반 DDL작성
  sql/schema.sql
Labels: documentation

#140 'prod'프로필 이름을 'staging'로 변경
  Dockerfile
  src/main/java/site/hirecruit/hr/global/config/LocalCorsConfig.kt
  src/main/java/site/hirecruit/hr/global/dummy/SetDummyData.kt
  src/main/java/site/hirecruit/hr/global/security/SecurityConfig.kt
  src/main/resources/application-staging.yml
Labels: documentation

#139 Feature local프로필 전용 oauth2 property 적용
  src/main/resources/application-local.yml
Labels: documentation

#141 Hotfix profile properties 올바르지 않은 이름변경
  src/main/resources/application-prod-test.yml
  src/main/resources/application-prod.yml
Labels: hotfix

#143 Add application timeZone
  src/main/java/site/hirecruit/hr/HRApplication.kt
Labels: documentation, enhancement, DevOps

#144 Spring Security prod프로필 config
  src/main/java/site/hirecruit/hr/global/config/EmbeddedRedisConfig.kt
  src/main/java/site/hirecruit/hr/global/config/LocalCorsConfig.kt
  src/main/java/site/hirecruit/hr/global/data/ServerProfile.kt
  src/main/java/site/hirecruit/hr/global/dummy/SetDummyData.kt
  src/main/java/site/hirecruit/hr/global/security/SecurityConfig.kt
  src/main/resources/application-local.yml
  src/main/resources/application-prod.yml
  src/main/resources/application-staging.yml
  src/main/resources/application.yml
Labels: documentation

#145 Revert "Update 필요없는 properties 제거"
  src/main/resources/application-local.yml
  src/main/resources/application-prod.yml
  src/main/resources/application-staging.yml
  src/main/resources/application.yml
Labels: hotfix

#146 Prod환경 cors설정
  src/main/java/site/hirecruit/hr/global/config/WebMvcArgumentResolversConfig.kt
  src/main/java/site/hirecruit/hr/global/config/WebMvcCorsConfig.kt
Labels: documentation

#149 endpoint 권한설정
  src/main/java/site/hirecruit/hr/global/security/SecurityConfig.kt
Labels: documentation

#151 Feature/amazon rds connection prod
  .gitignore
  build.gradle.kts
  sql/ddl.sql
  src/main/resources/application-prod.yml
  src/main/resources/application-staging.yml
  src/main/resources/static/docs/index.html
Labels: documentation, enhancement, Not completed, DevOps

#153 Fix mysql connection timeout EX
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
Labels: bug, hotfix

#154 Application 실행시점에 data.sql 실행
  src/main/resources/application-prod.yml
  src/main/resources/data.sql
Labels: documentation

#155 Develop
  .github/workflows/github-action-ci-script.yml
  .github/workflows/github-action-ecs-cd.yml
  .github/workflows/github-action-test-cd-script.yml
  .gitignore
  Dockerfile
  appspec.yml
  build.gradle.kts
  eventUpdate.md
  execute-deploy.sh
  sql/ddl.sql
  src/main/java/site/hirecruit/hr/HRApplication.kt
  src/main/java/site/hirecruit/hr/domain/company/validator/CompanyExistValidator.kt
  src/main/java/site/hirecruit/hr/domain/company/validator/annoation/CompanyIsNotExistByCompanyId.kt
  src/main/java/site/hirecruit/hr/domain/worker/dto/WorkerDto.kt
  src/main/java/site/hirecruit/hr/global/config/EmbeddedRedisConfig.kt
  src/main/java/site/hirecruit/hr/global/config/LocalCorsConfig.kt
  src/main/java/site/hirecruit/hr/global/config/WebMvcArgumentResolversConfig.kt
  src/main/java/site/hirecruit/hr/global/config/WebMvcCorsConfig.kt
  src/main/java/site/hirecruit/hr/global/data/ServerProfile.kt
  src/main/java/site/hirecruit/hr/global/dummy/SetDummyData.kt
  src/main/java/site/hirecruit/hr/global/security/SecurityConfig.kt
  src/main/java/site/hirecruit/hr/global/security/filter/SecurityExceptionResolverFilter.kt
  src/main/java/site/hirecruit/hr/global/security/handler/CustomLogoutSuccessHandler.kt
  src/main/java/site/hirecruit/hr/global/security/handler/OAuthLoginSuccessHandler.kt
  src/main/java/site/hirecruit/hr/global/security/handler/SecurityExceptionHandler.kt
  src/main/java/site/hirecruit/hr/health/HealthCheckController.kt
  src/main/resources/application-local.yml
  src/main/resources/application-prod-test.yml
  src/main/resources/application-prod.yml
  src/main/resources/application-staging.yml
  src/main/resources/data.sql
  src/main/resources/static/docs/index.html
  task-definition.json
Labels: documentation, enhancement

#138 Feature/infra-structure
  assets/img/hr-backend-deploy-spec.png
Labels: documentation, DevOps

#156 Develop
  Dockerfile
  assets/img/hr-backend-deploy-spec.png
Labels: hotfix, DevOps

#157 login 성공 후 리다이렉트 시 로그인 여부를 query-parameter으로 전달
  src/main/java/site/hirecruit/hr/global/security/handler/OAuthLoginSuccessHandler.kt
Labels: documentation

#160 HTTP Option method의 모든 요청을 permitAll로 지정
  src/main/java/site/hirecruit/hr/global/security/SecurityConfig.kt
Labels: documentation, hotfix

#161 Swagger config 프로필 설정
  src/main/java/site/hirecruit/hr/global/swagger/SwaggerConfig.java
  src/main/java/site/hirecruit/hr/global/swagger/SwaggerConfig.kt
Labels: documentation

#162 Develop
  assets/img/hr-backend-deploy-spec.png
  src/main/java/site/hirecruit/hr/global/security/SecurityConfig.kt
  src/main/java/site/hirecruit/hr/global/security/handler/OAuthLoginSuccessHandler.kt
  src/main/java/site/hirecruit/hr/global/swagger/SwaggerConfig.java
  src/main/java/site/hirecruit/hr/global/swagger/SwaggerConfig.kt
Labels: documentation, enhancement

#163 staging 프로필은 github oauth test app을 사용하도록 변경
  src/main/resources/application-staging.yml
Labels: documentation, high

#164 Hotfix/introdution length
  src/main/java/site/hirecruit/hr/domain/worker/dto/WorkerDto.kt
  src/main/resources/application-staging.yml
Labels: hotfix

#165 Logout 성공시 NPE뜨는 원인
  src/main/java/site/hirecruit/hr/global/security/handler/CustomLogoutSuccessHandler.kt
Labels: hotfix

#166 Hotfix 회원가입 시 introduction의 length에 대한 제약조건 누락
  src/main/java/site/hirecruit/hr/domain/worker/dto/WorkerDto.kt
Labels: hotfix

#167 Hotfix Logout시 CustomSuccessHandler NPE
  src/main/java/site/hirecruit/hr/global/security/handler/CustomLogoutSuccessHandler.kt
Labels: hotfix

#169 Add logback-config target
  .gitignore
  src/main/resources/application-prod.yml
  src/main/resources/application-staging.yml
Labels: enhancement, hotfix, DevOps

#168 세션식별 쿠키이름을 SESSION에서 HRSESSION으로 변경
  src/main/resources/application-local.yml
  src/main/resources/application-prod.yml
  src/main/resources/application-staging.yml
Labels: documentation

#172 hotfix oauth2 login npe
  src/main/java/site/hirecruit/hr/domain/auth/dto/OAuthAttributes.kt
  src/main/java/site/hirecruit/hr/domain/auth/dto/UserRegistrationDto.kt
  src/main/java/site/hirecruit/hr/domain/auth/entity/TempUserEntity.kt
  src/main/java/site/hirecruit/hr/domain/auth/service/impl/TempUserRegistrationServiceImpl.kt
  src/main/java/site/hirecruit/hr/domain/auth/service/impl/UserRegistrationServiceWithoutEmailAuthentication.kt
  src/main/java/site/hirecruit/hr/domain/auth/service/impl/UserSessionAuthServiceImpl.kt
  src/test/java/site/hirecruit/hr/domain/auth/aop/UserAuthAspectTest.kt
  src/test/java/site/hirecruit/hr/domain/auth/service/OAuth2ProcessorFacadeImplTest.kt
  src/test/java/site/hirecruit/hr/domain/auth/service/impl/TempUserRegistrationServiceImplTest.kt
  src/test/java/site/hirecruit/hr/domain/auth/service/impl/UserRegistrationServiceImplTest.kt
  src/test/java/site/hirecruit/hr/domain/auth/service/impl/UserRegistrationServiceWithoutEmailAuthenticationTest.kt
  src/test/java/site/hirecruit/hr/domain/auth/service/impl/UserSessionAuthServiceImplTest.kt
Labels: hotfix

#173 Develop
  src/main/java/site/hirecruit/hr/domain/auth/dto/OAuthAttributes.kt
  src/main/java/site/hirecruit/hr/domain/auth/dto/UserRegistrationDto.kt
  src/main/java/site/hirecruit/hr/domain/auth/entity/TempUserEntity.kt
  src/main/java/site/hirecruit/hr/domain/auth/service/impl/TempUserRegistrationServiceImpl.kt
  src/main/java/site/hirecruit/hr/domain/auth/service/impl/UserRegistrationServiceWithoutEmailAuthentication.kt
  src/main/java/site/hirecruit/hr/domain/auth/service/impl/UserSessionAuthServiceImpl.kt
  src/main/java/site/hirecruit/hr/domain/worker/dto/WorkerDto.kt
  src/test/java/site/hirecruit/hr/domain/auth/aop/UserAuthAspectTest.kt
  src/test/java/site/hirecruit/hr/domain/auth/service/OAuth2ProcessorFacadeImplTest.kt
  src/test/java/site/hirecruit/hr/domain/auth/service/impl/TempUserRegistrationServiceImplTest.kt
  src/test/java/site/hirecruit/hr/domain/auth/service/impl/UserRegistrationServiceImplTest.kt
  src/test/java/site/hirecruit/hr/domain/auth/service/impl/UserRegistrationServiceWithoutEmailAuthenticationTest.kt
  src/test/java/site/hirecruit/hr/domain/auth/service/impl/UserSessionAuthServiceImplTest.kt
Labels: documentation, hotfix

#174 Feature worker 전체조회 순서 무작위
  src/main/java/site/hirecruit/hr/domain/worker/service/WorkerLockupServiceImpl.kt
Labels: documentation

#175 Fix logout시 잔류 세션관련 쿠키 제거
  src/main/java/site/hirecruit/hr/global/security/handler/CustomLogoutSuccessHandler.kt
Labels: documentation

#176 FIx userRegistrationDto validator 적용되지 않은 문제 해결
  src/main/java/site/hirecruit/hr/domain/auth/dto/UserRegistrationDto.kt
  src/test/java/site/hirecruit/hr/domain/auth/aop/UserRegistrationAspectTest.kt
  src/test/java/site/hirecruit/hr/domain/auth/service/impl/UserRegistrationServiceImplTest.kt
  src/test/java/site/hirecruit/hr/domain/auth/service/impl/UserRegistrationServiceWithoutEmailAuthenticationTest.kt
Labels: hotfix

#177 Update redis.host
  Dockerfile
Labels: DevOps

#178 Develop
  src/main/java/site/hirecruit/hr/domain/auth/dto/UserRegistrationDto.kt
  src/main/java/site/hirecruit/hr/domain/worker/service/WorkerLockupServiceImpl.kt
  src/main/java/site/hirecruit/hr/global/security/handler/CustomLogoutSuccessHandler.kt
  src/test/java/site/hirecruit/hr/domain/auth/aop/UserRegistrationAspectTest.kt
  src/test/java/site/hirecruit/hr/domain/auth/service/impl/UserRegistrationServiceImplTest.kt
  src/test/java/site/hirecruit/hr/domain/auth/service/impl/UserRegistrationServiceWithoutEmailAuthenticationTest.kt
Labels: documentation

#179 Hotfix 잔류 쿠키 제거 전용 쿠키에 secure추가
  src/main/java/site/hirecruit/hr/global/security/handler/CustomLogoutSuccessHandler.kt
Labels: hotfix

#183 운영에서 발생한 request.cookies npe 해결
  src/main/java/site/hirecruit/hr/global/security/handler/CustomLogoutSuccessHandler.kt
Labels: hotfix

#187 Fix json mapping
  Dockerfile
  src/main/java/site/hirecruit/hr/domain/auth/dto/UserRegistrationDto.kt
Labels: hotfix

#188 Fix json mapping
  src/main/java/site/hirecruit/hr/domain/auth/dto/UserRegistrationDto.kt
Labels: hotfix

#190 Oauth 로그인시 USER_TYPE cookie 제공
  src/main/java/site/hirecruit/hr/global/security/handler/CustomLogoutSuccessHandler.kt
  src/main/java/site/hirecruit/hr/global/security/handler/OAuthLoginSuccessHandler.kt
  src/main/java/site/hirecruit/hr/global/security/handler/v1_0/OAuthLoginSuccessHandler.kt
Labels: documentation

#191 Feature/user role
  src/main/java/site/hirecruit/hr/domain/auth/entity/Role.kt
  src/main/java/site/hirecruit/hr/global/dummy/SetDummyData.kt
  src/main/java/site/hirecruit/hr/global/security/SecurityConfig.kt
Labels: documentation

#192 /auth/registration 호출시 USER_TYPE 쿠키에 사용자 role 반환
  src/main/java/site/hirecruit/hr/domain/auth/controller/AuthController.kt
  src/main/java/site/hirecruit/hr/global/util/CookieMakerUtil.kt
Labels: documentation

#195 회원가입시 저장되는 회원의 url UNAUTHENTICATED_EMAIL에서 WORKER로 변경
  src/main/java/site/hirecruit/hr/domain/auth/service/impl/UserRegistrationServiceImpl.kt
Labels: documentation

#197 유저 인증 실패 핸들러
  src/main/java/site/hirecruit/hr/global/security/SecurityConfig.kt
  src/main/java/site/hirecruit/hr/global/security/handler/CustomAuthenticationFailureHandler.kt
  src/main/java/site/hirecruit/hr/global/security/handler/SecurityExceptionHandler.kt
Labels: documentation, hotfix

#199 누락한 exception handling logging 추가
  src/main/java/site/hirecruit/hr/global/security/handler/SecurityExceptionHandler.kt
Labels: hotfix

#193 Feature/aws ses send email
  build.gradle.kts
  src/main/java/site/hirecruit/hr/thirdParty/aws/service/SesCredentialService.kt
  src/main/java/site/hirecruit/hr/thirdParty/aws/ses/dto/SesRequestDto.kt
  src/main/java/site/hirecruit/hr/thirdParty/aws/ses/service/HrSesService.kt
  src/main/java/site/hirecruit/hr/thirdParty/aws/ses/service/HrSesServiceImpl.kt
  src/main/java/site/hirecruit/hr/thirdParty/aws/ses/service/SesPurposeOfUse.kt
  src/main/java/site/hirecruit/hr/thirdParty/aws/ses/service/component/templateEmail/SesTemplateEmailComponent.kt
  src/main/java/site/hirecruit/hr/thirdParty/aws/ses/service/component/templateEmail/SesTemplateEmailComponentImpl.kt
  src/test/java/site/hirecruit/hr/thirdParty/aws/sns/service/HrSesServiceTest.kt
Labels: documentation, enhancement

#200 Feature/verifyEmail [사용자에게 인증번호 보내기]
  src/main/java/site/hirecruit/hr/domain/mailer/verifyEmail/component/VerificationCodeEmailTemplate.kt
  src/main/java/site/hirecruit/hr/domain/mailer/verifyEmail/service/VerificationEmailSenderService.kt
  src/main/java/site/hirecruit/hr/domain/mentor/service/MentorService.kt
  src/main/java/site/hirecruit/hr/domain/mentor/service/MentorServiceImpl.kt
  src/main/java/site/hirecruit/hr/domain/mentor/verify/entity/MentorEmailVerificationCodeEntity.kt
  src/main/java/site/hirecruit/hr/domain/mentor/verify/repository/MentorEmailVerificationCodeRepository.kt
  src/main/java/site/hirecruit/hr/domain/mentor/verify/service/MentorVerificationService.kt
  src/main/java/site/hirecruit/hr/domain/mentor/verify/service/MentorVerificationServiceImpl.kt
  src/main/java/site/hirecruit/hr/domain/worker/repository/WorkerRepository.kt
  src/main/java/site/hirecruit/hr/global/dummy/SetDummyData.kt
  src/main/java/site/hirecruit/hr/global/util/Utils.kt
  src/main/java/site/hirecruit/hr/thirdParty/aws/ses/service/HrSesService.kt
  src/main/java/site/hirecruit/hr/thirdParty/aws/ses/service/HrSesServiceImpl.kt
  src/main/java/site/hirecruit/hr/thirdParty/aws/ses/service/component/templateEmail/SesTemplateEmailComponentImpl.kt
  src/test/java/site/hirecruit/hr/domain/mentor/verify/service/MentorVerificationServiceImplTest.kt
  src/test/java/site/hirecruit/hr/global/util/UtilsKtTest.kt
  src/test/java/site/hirecruit/hr/thirdParty/aws/sns/service/HrSesServiceTest.kt
Labels: documentation, enhancement

#201 Fix 401, 403 error에 대한 cors에러
  src/main/java/site/hirecruit/hr/global/security/SecurityConfig.kt
  src/main/java/site/hirecruit/hr/global/security/handler/CustomAuthenticationEntryPoint.kt
  src/main/java/site/hirecruit/hr/global/security/handler/SecurityExceptionHandler.kt
Labels: hotfix

#202 company 중복 검증 로직
  src/main/java/site/hirecruit/hr/domain/company/dto/CompanyDto.kt
  src/main/java/site/hirecruit/hr/domain/company/repository/CompanyRepository.kt
  src/main/java/site/hirecruit/hr/domain/company/validator/CompanyDuplicateValidator.kt
  src/main/java/site/hirecruit/hr/domain/company/validator/annoation/CompanyNotDuplicate.kt
  src/main/java/site/hirecruit/hr/global/exception/GlobalExceptionHandler.kt
Labels: documentation

#204 temp_user table ddl 생성
  src/main/resources/data.sql
Labels: documentation

#203 Feature/verify verification code [사용자가 입력한 인증번호 검증]
  src/main/java/site/hirecruit/hr/domain/mentor/verify/entity/MentorEmailVerificationCodeEntity.kt
  src/main/java/site/hirecruit/hr/domain/mentor/verify/service/MentorVerificationServiceImpl.kt
  src/test/java/site/hirecruit/hr/domain/mentor/verify/service/MentorVerificationServiceImplTest.kt
  src/test/java/site/hirecruit/hr/thirdParty/aws/sns/service/HrSesServiceTest.kt
Labels: documentation, enhancement

#205 Feature/grant-mentor [Role 을 worker -> mentor]
  src/main/java/site/hirecruit/hr/domain/auth/entity/UserEntity.kt
  src/main/java/site/hirecruit/hr/domain/mentor/service/MentorService.kt
  src/main/java/site/hirecruit/hr/domain/mentor/service/MentorServiceImpl.kt
  src/main/java/site/hirecruit/hr/domain/mentor/verify/service/MentorVerificationServiceImpl.kt
  src/test/java/site/hirecruit/hr/domain/mentor/service/MentorServiceImplTest.kt
Labels: documentation, enhancement, question, healthy

#206 애플리케이션 profile별로 oauth2 app 나눔
  src/main/resources/application-local.yml
  src/main/resources/application-staging.yml
Labels: documentation

#210 hotfix/서버에서 로그인된 worker를 재인증/인가 할 필요 없다.
  src/main/java/site/hirecruit/hr/domain/mentor/controller/MentorController.kt
  src/main/java/site/hirecruit/hr/domain/mentor/service/MentorService.kt
  src/main/java/site/hirecruit/hr/domain/mentor/service/MentorServiceImpl.kt
  src/main/java/site/hirecruit/hr/domain/worker/repository/WorkerRepository.kt
  src/test/java/site/hirecruit/hr/domain/mentor/service/MentorServiceImplTest.kt
  src/test/java/site/hirecruit/hr/domain/mentor/verify/service/MentorVerificationServiceImplTest.kt
Labels: hotfix, high

#213 Develop
  src/main/java/site/hirecruit/hr/domain/auth/aop/UserUpdateColumnsVerifierAspect.kt
  src/main/java/site/hirecruit/hr/domain/auth/controller/UserController.kt
  src/main/java/site/hirecruit/hr/domain/auth/dto/UserUpdateDto.kt
  src/main/java/site/hirecruit/hr/domain/auth/entity/UserEntity.kt
  src/main/java/site/hirecruit/hr/domain/auth/service/UserUpdateService.kt
  src/main/java/site/hirecruit/hr/domain/auth/service/impl/UserUpdateServiceImpl.kt
  src/main/java/site/hirecruit/hr/domain/mentor/aop/MentorServiceAspect.kt
  src/main/java/site/hirecruit/hr/domain/mentor/controller/MentorController.kt
  src/main/java/site/hirecruit/hr/domain/mentor/dto/MentorDto.kt
  src/main/java/site/hirecruit/hr/domain/mentor/service/MentorService.kt
  src/main/java/site/hirecruit/hr/domain/mentor/service/MentorServiceImpl.kt
  src/main/java/site/hirecruit/hr/domain/mentor/verify/service/MentorVerificationServiceImpl.kt
  src/main/java/site/hirecruit/hr/domain/worker/dto/WorkerDto.kt
  src/main/java/site/hirecruit/hr/domain/worker/repository/WorkerCustomRepositoryImpl.kt
  src/main/java/site/hirecruit/hr/domain/worker/repository/WorkerRepository.kt
  src/main/java/site/hirecruit/hr/domain/worker/service/AuthUserWorkerServiceImpl.kt
  src/main/java/site/hirecruit/hr/domain/worker/service/WorkerRegistrationServiceImpl.kt
  src/main/java/site/hirecruit/hr/global/dummy/SetDummyData.kt
  src/main/java/site/hirecruit/hr/global/security/SecurityConfig.kt
  src/main/resources/application-local.yml
  src/main/resources/application-staging.yml
  src/test/java/site/hirecruit/hr/domain/mentor/service/MentorServiceImplTest.kt
  src/test/java/site/hirecruit/hr/domain/mentor/verify/service/MentorVerificationServiceImplTest.kt
  src/test/java/site/hirecruit/hr/domain/worker/service/WorkerLockupServiceImplTest.kt
Labels: documentation, enhancement

#214 User에 GithubLoginId 필드 추가 및 배치 로직 작성
  build.gradle.kts
  src/main/java/site/hirecruit/hr/HRApplication.kt
  src/main/java/site/hirecruit/hr/batch/github_login_id/job/AddGithubLoginIdJobConfiguration.kt
  src/main/java/site/hirecruit/hr/batch/github_login_id/service/LockupGithubLoginIdService.kt
  src/main/java/site/hirecruit/hr/domain/auth/dto/AuthUserInfo.kt
  src/main/java/site/hirecruit/hr/domain/auth/dto/OAuthAttributes.kt
  src/main/java/site/hirecruit/hr/domain/auth/entity/TempUserEntity.kt
  src/main/java/site/hirecruit/hr/domain/auth/entity/UserEntity.kt
  src/main/java/site/hirecruit/hr/domain/auth/repository/UserCustomRepositoryImpl.kt
  src/main/java/site/hirecruit/hr/domain/auth/service/impl/TempUserRegistrationServiceImpl.kt
  src/main/java/site/hirecruit/hr/domain/auth/service/impl/UserRegistrationRollbackServiceImpl.kt
  src/main/java/site/hirecruit/hr/domain/auth/service/impl/UserRegistrationServiceImpl.kt
  src/main/java/site/hirecruit/hr/domain/auth/service/impl/UserSessionAuthServiceImpl.kt
  src/main/java/site/hirecruit/hr/domain/mentor/aop/MentorServiceAspect.kt
  src/main/java/site/hirecruit/hr/global/dummy/SetDummyData.kt
  src/main/resources/application-local.yml
  src/main/resources/application-staging.yml
  src/test/java/site/hirecruit/hr/domain/auth/aop/UserRegistrationAspectTest.kt
  src/test/java/site/hirecruit/hr/domain/auth/aop/UserSessionInfoUpdateAspectTest.kt
  src/test/java/site/hirecruit/hr/domain/auth/repository/UserCustomRepositoryImplTest.kt
  src/test/java/site/hirecruit/hr/domain/auth/service/OAuth2ProcessorFacadeImplTest.kt
  src/test/java/site/hirecruit/hr/domain/auth/service/impl/TempUserRegistrationServiceImplTest.kt
  src/test/java/site/hirecruit/hr/domain/auth/service/impl/UserRegistrationRollbackServiceImplTest.kt
  src/test/java/site/hirecruit/hr/domain/auth/service/impl/UserRegistrationServiceTest.kt
  src/test/java/site/hirecruit/hr/domain/auth/service/impl/UserSessionAuthServiceImplTest.kt
  src/test/java/site/hirecruit/hr/domain/company/service/CompanyServiceTest.kt
  src/test/java/site/hirecruit/hr/domain/mentor/service/MentorServiceImplTest.kt
  src/test/java/site/hirecruit/hr/domain/worker/service/AuthUserWorkerServiceImplTest.kt
  src/test/java/site/hirecruit/hr/domain/worker/service/WorkerRegistrationServiceImplTest.kt
Labels: documentation

#216 Fix [domain:: worker] data consistency
  src/main/java/site/hirecruit/hr/domain/worker/service/AuthUserWorkerServiceImpl.kt
Labels: bug, hotfix

#217 기본 정보 수정시 session 데이터 동기화
  src/main/java/site/hirecruit/hr/domain/auth/aop/UserSessionInfoUpdateAspect.kt
  src/main/java/site/hirecruit/hr/domain/auth/service/UserUpdateService.kt
  src/main/java/site/hirecruit/hr/domain/auth/service/impl/UserUpdateServiceImpl.kt
Labels: documentation, hotfix

#219 Spring batch에 필요한 ddl 작성
  src/main/resources/application-prod.yml
  src/main/resources/batch-application.sql
Labels: documentation

#218 data.sql user ddl에 github_login_id 컬럼 구문 추가
  sql/ddl.sql
  src/main/resources/data.sql
Labels: documentation, enhancement

#220 1.2.1
  build.gradle.kts
  sql/ddl.sql
  src/main/java/site/hirecruit/hr/HRApplication.kt
  src/main/java/site/hirecruit/hr/batch/github_login_id/job/AddGithubLoginIdJobConfiguration.kt
  src/main/java/site/hirecruit/hr/batch/github_login_id/service/LockupGithubLoginIdService.kt
  src/main/java/site/hirecruit/hr/domain/auth/aop/UserSessionInfoUpdateAspect.kt
  src/main/java/site/hirecruit/hr/domain/auth/dto/AuthUserInfo.kt
  src/main/java/site/hirecruit/hr/domain/auth/dto/OAuthAttributes.kt
  src/main/java/site/hirecruit/hr/domain/auth/entity/TempUserEntity.kt
  src/main/java/site/hirecruit/hr/domain/auth/entity/UserEntity.kt
  src/main/java/site/hirecruit/hr/domain/auth/repository/UserCustomRepositoryImpl.kt
  src/main/java/site/hirecruit/hr/domain/auth/service/UserUpdateService.kt
  src/main/java/site/hirecruit/hr/domain/auth/service/impl/TempUserRegistrationServiceImpl.kt
  src/main/java/site/hirecruit/hr/domain/auth/service/impl/UserRegistrationRollbackServiceImpl.kt
  src/main/java/site/hirecruit/hr/domain/auth/service/impl/UserRegistrationServiceImpl.kt
  src/main/java/site/hirecruit/hr/domain/auth/service/impl/UserSessionAuthServiceImpl.kt
  src/main/java/site/hirecruit/hr/domain/auth/service/impl/UserUpdateServiceImpl.kt
  src/main/java/site/hirecruit/hr/domain/mentor/aop/MentorServiceAspect.kt
  src/main/java/site/hirecruit/hr/domain/worker/dto/WorkerDto.kt
  src/main/java/site/hirecruit/hr/domain/worker/repository/WorkerCustomRepositoryImpl.kt
  src/main/java/site/hirecruit/hr/domain/worker/service/AuthUserWorkerServiceImpl.kt
  src/main/java/site/hirecruit/hr/domain/worker/service/WorkerRegistrationServiceImpl.kt
  src/main/java/site/hirecruit/hr/global/dummy/SetDummyData.kt
  src/main/resources/application-local.yml
  src/main/resources/application-prod.yml
  src/main/resources/application-staging.yml
  src/main/resources/batch-application.sql
  src/main/resources/data.sql
  src/test/java/site/hirecruit/hr/domain/auth/aop/UserRegistrationAspectTest.kt
  src/test/java/site/hirecruit/hr/domain/auth/aop/UserSessionInfoUpdateAspectTest.kt
  src/test/java/site/hirecruit/hr/domain/auth/repository/UserCustomRepositoryImplTest.kt
  src/test/java/site/hirecruit/hr/domain/auth/service/OAuth2ProcessorFacadeImplTest.kt
  src/test/java/site/hirecruit/hr/domain/auth/service/impl/TempUserRegistrationServiceImplTest.kt
  src/test/java/site/hirecruit/hr/domain/auth/service/impl/UserRegistrationRollbackServiceImplTest.kt
  src/test/java/site/hirecruit/hr/domain/auth/service/impl/UserRegistrationServiceTest.kt
  src/test/java/site/hirecruit/hr/domain/auth/service/impl/UserSessionAuthServiceImplTest.kt
  src/test/java/site/hirecruit/hr/domain/company/service/CompanyServiceTest.kt
  src/test/java/site/hirecruit/hr/domain/mentor/service/MentorServiceImplTest.kt
  src/test/java/site/hirecruit/hr/domain/worker/service/AuthUserWorkerServiceImplTest.kt
  src/test/java/site/hirecruit/hr/domain/worker/service/WorkerLockupServiceImplTest.kt
  src/test/java/site/hirecruit/hr/domain/worker/service/WorkerRegistrationServiceImplTest.kt
Labels: documentation

#221 [운영환경] 기존 회원가입을 완료한 사용자에 대한 "githubLoginId update" 배치 비활성화
  src/main/java/site/hirecruit/hr/batch/github_login_id/job/AddGithubLoginIdJobConfiguration.kt
  src/main/resources/application-prod.yml
  src/main/resources/batch-application.sql
Labels: documentation

#222 사용자 기본 정보 수정 API Mentor가 email를 수정하면 WORKER로 강등
  src/main/java/site/hirecruit/hr/domain/auth/controller/UserController.kt
  src/main/java/site/hirecruit/hr/domain/auth/entity/UserEntity.kt
  src/main/java/site/hirecruit/hr/domain/auth/service/impl/UserUpdateServiceImpl.kt
Labels: documentation

#223 Refactoring Worker Update logic
  src/main/java/site/hirecruit/hr/domain/company/validator/annoation/CompanyIsNotExistByCompanyId.kt
  src/main/java/site/hirecruit/hr/domain/worker/aop/WorkerUpdateColumnsVerifierAspect.kt
  src/main/java/site/hirecruit/hr/domain/worker/dto/WorkerDto.kt
  src/main/java/site/hirecruit/hr/domain/worker/entity/WorkerEntity.kt
  src/main/java/site/hirecruit/hr/domain/worker/service/AuthUserWorkerServiceImpl.kt
  src/test/java/site/hirecruit/hr/domain/worker/aop/WorkerUpdateColumnsVerifierAspectTest.kt
  src/test/java/site/hirecruit/hr/domain/worker/service/AuthUserWorkerServiceImplTest.kt
Labels: documentation

#224 Refactoring user update feature
  src/main/java/site/hirecruit/hr/domain/auth/aop/UserUpdateColumnsVerifierAspect.kt
  src/main/java/site/hirecruit/hr/domain/auth/dto/UserUpdateDto.kt
  src/main/java/site/hirecruit/hr/domain/auth/entity/UserEntity.kt
  src/main/java/site/hirecruit/hr/domain/auth/service/impl/UserUpdateServiceImpl.kt
Labels: documentation

#225 Oauth2 예외 authorization_request_not_found 핸들링
  src/main/java/site/hirecruit/hr/global/security/handler/SecurityExceptionHandler.kt
Labels: documentation
