Repository themoment-team/HiRecruit-server, pull requests merged in 2022-03, with the labels that each got.

#5 Github OAuth2 사전준비
  .gitignore
  build.gradle
  src/main/java/site/hirecruit/hr/domain/auth/service/CustomOAuth2UserService.java
  src/main/java/site/hirecruit/hr/domain/worker/entity/WorkerEntity.java
  src/main/java/site/hirecruit/hr/global/security/SecurityConfig.java
  src/main/resources/application.yml
Labels: healthy

#6 Feature/jacoco settings
  build.gradle
  lombok.config
  src/main/java/site/hirecruit/hr/domain/anonymous/dto/AnonymousDto.java
  src/main/java/site/hirecruit/hr/domain/anonymous/entity/AnonymousEntity.java
  src/main/java/site/hirecruit/hr/domain/anonymous/repository/AnonymousRepository.java
  src/test/java/site/hirecruit/hr/domain/anonymous/entity/AnonymousEntityTest.java
Labels: enhancement, help wanted, invalid

#9 Update filter api uri for prod
  src/main/java/site/hirecruit/hr/global/swagger/SwaggerConfig.java
Labels: hotfix
