Repository themoment-team/HiRecruit-server, pull requests merged in 2022-07, with the labels that each got.

#227 Fix h2-console cors 해결
  src/main/java/site/hirecruit/hr/global/security/SecurityConfig.kt
Labels: documentation, hotfix

#228 Fix validator annotation 잘못 수정
  src/main/java/site/hirecruit/hr/domain/company/validator/annoation/CompanyIsNotExistByCompanyId.kt
  src/main/java/site/hirecruit/hr/domain/worker/dto/WorkerDto.kt
Labels: hotfix

#234 Feature/prod cd performance improve
  .github/workflows/github-action-ecs-cd.yml
  .github/workflows/github-action-test-cd-script.yml
  Dockerfile
  build.gradle.kts
  src/main/java/site/hirecruit/hr/domain/mentee/service/MenteeServiceImpl.kt
Labels: documentation, Not completed, DevOps

#236 Add ci step, bootJar
  .github/workflows/github-action-ci-script.yml
  .github/workflows/github-action-test-cd-script.yml
Labels: documentation, hotfix, DevOps

#238 Hotfix/ci script
  .github/workflows/github-action-ci-script.yml
Labels: hotfix, DevOps

#237 Feature/build script eidt
  .github/workflows/github-action-ecs-cd.yml
Labels: invalid, wontfix, DevOps

#239 Develop
  .github/workflows/github-action-ci-script.yml
  .github/workflows/github-action-ecs-cd.yml
  .github/workflows/github-action-test-cd-script.yml
Labels: bug, documentation, hotfix

#240 hotfix 애플리케이션 시작 후 sql 파일 db에 날리지 않음
  src/main/resources/application-prod.yml
Labels: hotfix

#242 Vo 클래스를 Dto로 이름 변경
  src/main/java/site/hirecruit/hr/domain/user/dto/RegularUserRegistrationDto.kt
  src/main/java/site/hirecruit/hr/domain/user/dto/RegularUserRegistrationRequestDto.kt
Labels: best-review

#244 Add RUN true sequence for solve issue #1
  Dockerfile
Labels: bug, DevOps

#245 Develop
  Dockerfile
  src/main/java/site/hirecruit/hr/domain/auth/service/TempUserRegistrationService.kt
  src/main/java/site/hirecruit/hr/domain/auth/service/impl/TempUserRegistrationServiceImpl.kt
  src/main/java/site/hirecruit/hr/domain/user/dto/CommonUserRegistrationDto.kt
  src/main/java/site/hirecruit/hr/domain/user/dto/RegularUserRegistrationDto.kt
  src/main/java/site/hirecruit/hr/domain/user/dto/RegularUserRegistrationRequestDto.kt
  src/main/java/site/hirecruit/hr/domain/user/dto/TempUserRegistrationDto.kt
  src/main/java/site/hirecruit/hr/domain/user/service/NewUserRegistrationService.kt
  src/main/java/site/hirecruit/hr/domain/user/service/TempUserRegistrationService.kt
  src/main/java/site/hirecruit/hr/domain/user/service/UserRegistrationService.kt
  src/main/java/site/hirecruit/hr/domain/user/service/UserRegistrationServiceImpl.kt
  src/main/java/site/hirecruit/hr/domain/user/service/WorkerUserRegistrationService.kt
Labels: documentation, improvement

#246 Add workpath arg and targeting jarfile like workpath/*.jar in entrypoint
  Dockerfile
Labels: bug, hotfix, DevOps

#247 Develop
  Dockerfile
Labels: hotfix, DevOps

#248 Hotfix/esc essential container in task exited
  .github/workflows/github-action-ecs-cd.yml
  Dockerfile
Labels: bug, hotfix, DevOps

#249 Develop
  .github/workflows/github-action-ecs-cd.yml
  Dockerfile
Labels: hotfix, DevOps

#253 Feature/docker build push in action
  .github/workflows/github-action-ci.yml
  .github/workflows/github-action-prod-cd.yml
  .github/workflows/github-action-test-cd.yml
  Dockerfile
Labels: documentation, DevOps, improvement

#254 Develop
  .github/workflows/github-action-ci.yml
  .github/workflows/github-action-prod-cd.yml
  .github/workflows/github-action-test-cd.yml
  Dockerfile
Labels: documentation, DevOps

#251 새로운 회원가입 로직 적용
  src/main/java/site/hirecruit/hr/domain/auth/controller/AuthController.kt
  src/main/java/site/hirecruit/hr/domain/user/controller/UserRegistrationController.kt
  src/main/java/site/hirecruit/hr/domain/user/service/NewUserRegistrationService.kt
  src/main/java/site/hirecruit/hr/domain/user/service/TempUserRegistrationService.kt
  src/main/java/site/hirecruit/hr/domain/user/service/UserRegistrationService.kt
  src/main/java/site/hirecruit/hr/domain/user/service/UserRegistrationServiceImpl.kt
  src/main/java/site/hirecruit/hr/domain/user/service/WorkerUserRegistrationService.kt
  src/test/java/site/hirecruit/hr/domain/auth/aop/UserRegistrationAspectTest.kt
  src/test/java/site/hirecruit/hr/domain/auth/service/impl/UserRegistrationServiceTest.kt
Labels: improvement

#256 Feature/gha cache lambda trigger
  .github/workflows/trigger-gha-cache-status-script.yml
Labels: documentation, enhancement, DevOps

#255 redis session namespace 변경
  src/main/resources/application-local.yml
  src/main/resources/application-staging.yml
Labels: DevOps

#260 [Revert] show response step 삭제가 http status `50x`를 피할 수 있는 방법이 아니였음.
  .github/workflows/trigger-gha-cache-status-script.yml
Labels: hotfix, Not completed

#259 Develop
  .github/workflows/trigger-gha-cache-status-script.yml
  src/main/java/site/hirecruit/hr/domain/auth/controller/AuthController.kt
  src/main/java/site/hirecruit/hr/domain/user/controller/UserRegistrationController.kt
  src/main/java/site/hirecruit/hr/domain/user/service/NewUserRegistrationService.kt
  src/main/java/site/hirecruit/hr/domain/user/service/TempUserRegistrationService.kt
  src/main/java/site/hirecruit/hr/domain/user/service/UserRegistrationService.kt
  src/main/java/site/hirecruit/hr/domain/user/service/UserRegistrationServiceImpl.kt
  src/main/java/site/hirecruit/hr/domain/user/service/WorkerUserRegistrationService.kt
  src/main/resources/application-local.yml
  src/main/resources/application-staging.yml
  src/test/java/site/hirecruit/hr/domain/auth/aop/UserRegistrationAspectTest.kt
  src/test/java/site/hirecruit/hr/domain/auth/service/impl/UserRegistrationServiceTest.kt
Labels: documentation, DevOps, improvement

#258 Migration/mentee erd v1.3
  src/main/java/site/hirecruit/hr/domain/mentee/dto/MenteeDto.kt
  src/main/java/site/hirecruit/hr/domain/mentee/entity/MenteeEntity.kt
  src/main/java/site/hirecruit/hr/domain/mentee/repository/MenteeRepository.kt
  src/main/java/site/hirecruit/hr/domain/mentee/service/MenteeService.kt
  src/main/java/site/hirecruit/hr/domain/mentee/service/MenteeServiceImpl.kt
  src/main/java/site/hirecruit/hr/global/dummy/SetDummyData.kt
  src/test/java/site/hirecruit/hr/domain/mentee/entity/MenteeEntityTest.kt
  src/test/java/site/hirecruit/hr/domain/mentee/service/MenteeCoreServiceTest.kt
Labels: documentation, improvement

#261 Add mentorEntity for satisfy erd spec v1.3
  src/main/java/site/hirecruit/hr/domain/mentor/entity/MentorEntity.kt
Labels: documentation, enhancement

#262 Update 변할 수 있는 feild 에 대해 var 선언
  src/main/java/site/hirecruit/hr/domain/mentee/entity/MenteeEntity.kt
  src/main/java/site/hirecruit/hr/domain/mentor/entity/MentorEntity.kt
Labels: bug, hotfix

#263 Update prod redis port
  Dockerfile
Labels: DevOps, improvement

#264 Develop
  Dockerfile
  src/main/java/site/hirecruit/hr/domain/mentee/dto/MenteeDto.kt
  src/main/java/site/hirecruit/hr/domain/mentee/entity/MenteeEntity.kt
  src/main/java/site/hirecruit/hr/domain/mentee/repository/MenteeRepository.kt
  src/main/java/site/hirecruit/hr/domain/mentee/service/MenteeService.kt
  src/main/java/site/hirecruit/hr/domain/mentee/service/MenteeServiceImpl.kt
  src/main/java/site/hirecruit/hr/domain/mentor/entity/MentorEntity.kt
  src/main/java/site/hirecruit/hr/global/dummy/SetDummyData.kt
  src/test/java/site/hirecruit/hr/domain/mentee/entity/MenteeEntityTest.kt
  src/test/java/site/hirecruit/hr/domain/mentee/service/MenteeCoreServiceTest.kt
Labels: documentation, DevOps, improvement

#265 worker.giveLink 필드 제거
  src/main/java/site/hirecruit/hr/domain/worker/dto/WorkerDto.kt
  src/main/java/site/hirecruit/hr/domain/worker/entity/WorkerEntity.kt
  src/main/java/site/hirecruit/hr/domain/worker/repository/WorkerCustomRepositoryImpl.kt
  src/main/java/site/hirecruit/hr/domain/worker/service/AuthUserWorkerServiceImpl.kt
  src/main/java/site/hirecruit/hr/domain/worker/service/WorkerRegistrationServiceImpl.kt
  src/test/java/site/hirecruit/hr/domain/worker/service/AuthUserWorkerServiceImplTest.kt
  src/test/java/site/hirecruit/hr/domain/worker/service/WorkerLockupServiceImplTest.kt
  src/test/java/site/hirecruit/hr/domain/worker/service/WorkerRegistrationServiceImplTest.kt
Labels: improvement

#270 MapStruct 도입
  build.gradle.kts
  src/main/java/site/hirecruit/hr/domain/auth/dto/mapper/AuthUserInfoMapper.kt
  src/main/java/site/hirecruit/hr/domain/auth/service/impl/UserSessionAuthServiceImpl.kt
  src/main/java/site/hirecruit/hr/domain/user/service/TempUserRegistrationService.kt
Labels: improvement
